#!/usr/bin/env python3
# Generate deterministic RSA-1024 vectors for Verilog simulation.
import random
from math import gcd

BITS = 1024
E = 65537
random.seed(20260517)

_SMALL_PRIMES = [3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97]

def is_probable_prime(n):
    if n < 2:
        return False
    for p in _SMALL_PRIMES:
        if n % p == 0:
            return n == p
    d = n - 1
    s = 0
    while d % 2 == 0:
        s += 1
        d //= 2
    # Deterministic enough for generated test vectors; not for production keygen.
    for a in [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]:
        if a >= n - 2:
            continue
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        ok = False
        for _ in range(s - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                ok = True
                break
        if not ok:
            return False
    return True

def gen_prime(bits):
    while True:
        n = random.getrandbits(bits)
        n |= (1 << (bits - 1)) | 1
        # ensure e and p-1 coprime
        if gcd(n - 1, E) != 1:
            continue
        if is_probable_prime(n):
            return n

def hx(x, width_bits=BITS):
    return f"{x:0{width_bits//4}x}"

p = gen_prime(BITS // 2)
q = gen_prime(BITS // 2)
while p == q:
    q = gen_prime(BITS // 2)
N = p * q
phi = (p - 1) * (q - 1)
d = pow(E, -1, phi)

msg = b"HELLO RSA 1024"
k = BITS // 8
ps_len = k - len(msg) - 3
# Deterministic non-zero PS for simulation. Real PKCS#1 v1.5 encryption needs random non-zero PS.
PS = bytes(((i % 255) + 1) for i in range(ps_len))
EM = b"\x00\x02" + PS + b"\x00" + msg
M = int.from_bytes(EM, "big")
C = pow(M, E, N)
M_DEC = pow(C, d, N)
R = 1 << BITS
R_MOD_N = R % N
R2_MOD_N = (R * R) % N
assert M < N
assert M_DEC == M

vh = f'''// Auto-generated by scripts/gen_vectors.py
`define RSA_N       1024'h{hx(N)}
`define RSA_E       1024'h{hx(E)}
`define RSA_D       1024'h{hx(d)}
`define RSA_M       1024'h{hx(M)}
`define RSA_C       1024'h{hx(C)}
`define RSA_R       1024'h{hx(R_MOD_N)}
`define RSA_R2      1024'h{hx(R2_MOD_N)}
'''
open("tb/rsa1024_vectors.vh", "w").write(vh)

print("N  =", hex(N))
print("e  =", hex(E))
print("d  =", hex(d))
print("M  =", hex(M))
print("C  =", hex(C))
print("R  =", hex(R_MOD_N))
print("R2 =", hex(R2_MOD_N))
